name: OreSpawners
version: 0.5.3
main: RKAbdul\OreSpawners\Main
authors: [RKAbdul, AGTHARN]
api: 4.0.0

commands:
 orespawner:
  description: Give ore spawner.
  permission: "orespawner.give"

permissions:
  orespawner.give:
    default: op
